ProyectoATECA/Models/Ficha.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoATECA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ficha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ficha()
        {
            this.HistorialAtendidos = new HashSet<HistorialAtendido>();
        }


        [Display(Name = "Identificador")]
        public int ID_ficha { get; set; }

        [Display(Name = "Servicio")]
        public int ID_servicio { get; set; }
        [Display(Name = "Código")]
        public string codigoFicha { get; set; }
        [Display(Name = "Fecha")]
        public System.DateTime fecha { get; set; }
        [Display(Name = "Atendido")]
        public string atendido { get; set; }
        [Display(Name = "Llamado")]
        public string llamado { get; set; }
        public string agendado { get; set; }

        [Display(Name = "Tipo de ficha")]
        public string tipoFicha { get; set; }

        public int ID_usuario { get; set; }

        public virtual Servicio Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialAtendido> HistorialAtendidos { get; set; }
    }
}

ProyectoATECA/Controllers/FichasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Speech.AudioFormat;
using System.Text;
//using System.Speech.Synthesis;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;
using ProyectoATECA.Hubs;
using ProyectoATECA.Models;




namespace ProyectoATECA.Controllers
{
    public class FichasController : Controller
    {
        DateTime central = TimeZoneInfo.ConvertTimeBySystemTimeZoneId(DateTime.Now, "Central Standard Time");

        private ATECA_BDEntities db = new ATECA_BDEntities();
        public FichasController() { }
        // GET: Fichas
        public ActionResult Index()
        {


            var fichas = db.Fichas.Include(f => f.Servicio);
            return View( 
                db.Fichas.Where(f => f.atendido == "No" && f.fecha.DayOfYear == central.DayOfYear).OrderBy(f => f.fecha));
        }

        public ActionResult GetFichasData()
        {
            int id_rol = Convert.ToInt32(System.Web.HttpContext.Current.Session["ROL"]);
            int id_servicio = Convert.ToInt32(System.Web.HttpContext.Current.Session["SERV"]);
            if (id_rol == 3)
            {
                return PartialView("_FichasData", db.Fichas.Where(f => f.atendido == "No" && f.tipoFicha == "Ley 7600" &&
                f.fecha.Day == central.Day &&
                f.fecha.Month == central.Month &&
                f.fecha.Year == central.Year
                ).ToList().OrderBy(f => f.fecha));
            }
            if (id_rol == 2)
            {
                if (id_servicio == 0)
                {
                    return PartialView("_FichasData", db.Fichas.Where(f => f.atendido == "No" && f.tipoFicha == "Regular" &&
                     f.fecha.Day == central.Day &&
                     f.fecha.Month == central.Month &&
                     f.fecha.Year == central.Year
                     ).ToList().OrderBy(f => f.fecha));
                }
                else
                {
                    return PartialView("_FichasData", db.Fichas.Where(f => f.atendido == "No" && f.tipoFicha == "Regular" &&
                    f.fecha.Day == central.Day &&
                    f.fecha.Month == central.Month &&
                    f.fecha.Year == central.Year &&
                    f.ID_servicio == id_servicio
                    ).ToList().OrderBy(f => f.fecha));
                }


            }
            else
            {
                return PartialView("_FichasData", db.Fichas.Where(f => f.atendido == "No" &&
                f.fecha.Day == central.Day &&
                f.fecha.Month == central.Month &&
                f.fecha.Year == central.Year
                ).ToList().OrderBy(f => f.fecha));
            }

        }

        //public ViewResult Index()
        //{
        //    var countries = new SelectList(
        //        db.Racers.Select(r => r.Country).Distinct().ToList());

        //    ViewBag.Countries = countries;
        //    return View();
        //}

        //public PartialViewResult RacersByCountryPartial(string id)
        //{
        //    return PartialView(
        //        db.Racers.Where(r => r.Country == id).OrderByDescending(r => r.Wins)
        //            .ThenBy(r => r.Lastname).ToList());
        //}

        // GET: Fichas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ficha ficha = db.Fichas.Find(id);
            if (ficha == null)
            {
                return HttpNotFound();
            }
            return View(ficha);
        }
        public ActionResult Escoger()
        {

            return View();
        }
        // GET: Fichas/Create

        public ActionResult Create()
        {
            ViewData["codigoFicha"] = DateTime.Now.Hour + "-" + DateTime.Now.Minute + "-" + DateTime.Now.Second;
            ViewData["fecha"] = DateTime.Now;
            ViewData["atendido"] = "No";
            ViewData["llamado"] = "No";
            ViewBag.ID_servicio = new SelectList(db.Servicios, "ID_servicio", "nombre");
            return View();
        }

        // POST: Fichas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_ficha,ID_servicio,codigoFicha,fecha,atendido,llamado,tipoFicha")] Ficha ficha)
        {
            if (ModelState.IsValid)
            {
                db.Fichas.Add(ficha);
                db.SaveChanges();
                FichasHub.BroadcastData();
                return RedirectToAction("Create");
            }

            ViewBag.ID_servicio = new SelectList(db.Servicios, "ID_servicio", "nombre", ficha.ID_servicio);
            return View(ficha);
        }

        public ActionResult Eliminar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ficha ficha = db.Fichas.Find(id);
            if (ficha == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_servicio = new SelectList(db.Servicios, "ID_servicio", "nombre", ficha.ID_servicio);
            return View(ficha);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar([Bind(Include = "ID_ficha,ID_servicio,codigoFicha,fecha,atendido,llamado,tipoFicha")] Ficha ficha)
        {
            if (ModelState.IsValid)
            {

                db.Entry(ficha).State = EntityState.Modified;
                db.SaveChanges();


                FichasHub.BroadcastData();
                FichasHub.BroadcastDataFILA();

                return RedirectToAction("Index");
            };
            ViewBag.ID_servicio = new SelectList(db.Servicios, "ID_servicio", "nombre", ficha.ID_servicio);

            return View(ficha);
        }



        public ActionResult Llamar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ficha ficha = db.Fichas.Find(id);
            if (ficha == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_servicio = new SelectList(db.Servicios, "ID_servicio", "nombre", ficha.ID_servicio);
            return View(ficha);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Llamar([Bind(Include = "ID_ficha,ID_servicio,codigoFicha,fecha,atendido,llamado,tipoFicha")] Ficha ficha)
        {
            if (ModelState.IsValid)
            {

                db.Entry(ficha).State = EntityState.Modified;
                db.SaveChanges();
                string nombreServicio = (from s in db.Servicios
                                         where s.ID_servicio == ficha.ID_servicio
                                         select s.nombre).FirstOrDefault();
                TTS("Ficha: " + ficha.codigoFicha + ". Caja: " + nombreServicio);

                FichasHub.BroadcastData();
                FichasHub.BroadcastDataFILA();
                FichasHub.BroadcastDataSonido();

                return RedirectToAction("Index");
            };
            ViewBag.ID_servicio = new SelectList(db.Servicios, "ID_servicio", "nombre", ficha.ID_servicio);

            return View(ficha);
        }



        private string subscriptionKey;
        private string tokenFetchUri;
        public FichasController(string tokenFetchUri, string subscriptionKey)
        {
            if (string.IsNullOrWhiteSpace(tokenFetchUri))
            {
                throw new ArgumentNullException(nameof(tokenFetchUri));
            }
            if (string.IsNullOrWhiteSpace(subscriptionKey))
            {
                throw new ArgumentNullException(nameof(subscriptionKey));
            }
            this.tokenFetchUri = tokenFetchUri;
            this.subscriptionKey = subscriptionKey;
        }

        public async Task<string> FetchTokenAsync()
        {
            using (HttpClient client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", this.subscriptionKey);
                UriBuilder uriBuilder = new UriBuilder(this.tokenFetchUri);
                HttpResponseMessage result = await client.PostAsync(uriBuilder.Uri.AbsoluteUri, null).ConfigureAwait(false);
                return await result.Content.ReadAsStringAsync().ConfigureAwait(false);
            }
        }


        public async Task TTS(string text)
        {
            // Prompts the user to input text for TTS conversion
            Console.Write("What would you like to convert to speech? ");
            //string text = "hello trump";

            // Gets an access token
            string accessToken;
            Console.WriteLine("Attempting token exchange. Please wait...\n");

            // Add your subscription key here
            // If your resource isn't in WEST US, change the endpoint
            FichasController auth = new FichasController("https://westus.api.cognitive.microsoft.com/sts/v1.0/issueToken", "dcce377c0a8a440f807423636ed9f506");
            try
            {

                accessToken = await auth.FetchTokenAsync().ConfigureAwait(false);
                Console.WriteLine("Successfully obtained an access token. \n");
            }
            catch (Exception ex)
            {

ProyectoATECA/Views/Fichas/Create.cshtml
@model ProyectoATECA.Models.Ficha

@{
    ViewBag.Title = "Crear";
    ViewBag.TipoFicha = Request["tipoFicha"];

}

<h2>Solicite su ficha según el servicio que desee</h2>
@ViewBag.TipoFicha

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ficha</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_servicio, "Servicio", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_servicio", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_servicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.tipoFicha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.tipoFicha, new { @Value = @ViewBag.TipoFicha, htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.codigoFicha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.codigoFicha, new { @Value = ViewData["codigoFicha"], htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.codigoFicha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.fecha, new { @Value = ViewData["fecha"], htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.atendido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.atendido, new { @Value = ViewData["atendido"], htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.atendido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.llamado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.llamado, new { @Value = ViewData["llamado"], htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.llamado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Solicitar ficha" class="btn btn-default" />
            </div>


        </div>


    </div>

}

ProyectoATECA/Views/Fichas/Eliminar.cshtml
@model ProyectoATECA.Models.Ficha

@{
    ViewBag.Title = "Eliminar";
    ViewData["atendido"] = "No se presentó";
    ViewData["llamado"] = "Si";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <div class="alert alert-danger">
        <h1>¿Está seguro que desea eliminar esta ficha?</h1>
    </div>
    <div class="jumbotron">

        <div class="d-flex w-100 justify-content-between">
            <h2 class="mb-1">Ficha @Model.codigoFicha.ToString()</h2>
            <h5 class="text-muted">@Model.fecha</h5>
        </div>
        <hr class="my-3">
        <h2 class="mb-1">Caja</h2>
        <h3 class="text-muted">@Model.ID_servicio.ToString()</h3>

    </div>
    <br>
    @*<dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ID_servicio)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ID_servicio)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.codigoFicha)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.codigoFicha)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.fecha)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.fecha)
            </dd>
        </dl>*@

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_ficha)

    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.ID_servicio, "ID_servicio", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ID_servicio", null, htmlAttributes: new { @class = "form-control", })
        </div>
    </div>

    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.codigoFicha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.codigoFicha, new { htmlAttributes = new { @class = "form-control", } })
        </div>
    </div>

    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control", } })
        </div>
    </div>

    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.atendido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.atendido, new { @Value = ViewData["atendido"], htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.llamado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.llamado, new { @Value = ViewData["llamado"], htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>


    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.tipoFicha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.tipoFicha, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-0 col-md-10">
            <input type="submit" value="Eliminar" class="btn btn-danger" />
        </div>
    </div>
</div>

}
<br>
<div>
    @Html.ActionLink("Regresar", "Index")
</div>

ProyectoATECA/Views/Fichas/Escoger.cshtml
@model IEnumerable<ProyectoATECA.Models.Ficha>

@{
    /**/

    ViewBag.Title = "Escoger tipo de servicio";
}

<h2>Tipo de servicio</h2>

<p>

</p>
<div class="row">
    <div class="col-md-4">
        @Html.ActionLink("Servicio regular", "Create", "Fichas", new { @tipoFicha = "Servicio regular" }, new { @class = "btn btn-default" })
    </div>
    <div class="col-md-4">
        @Html.ActionLink("Ley 7600", "Create", "Fichas", new { @tipoFicha = "Ley 7600" }, new { @class = "btn btn-default" })

    </div>
</div>

ProyectoATECA/Views/Fichas/Index.cshtml
@model IEnumerable<ProyectoATECA.Models.Ficha>

@{
    ViewBag.Title = "Fichas";
}

<div id="dataModel"></div>
@section JavaScript{
    <script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script type="text/javascript">
        $(function () {
            var hubNotify = $.connection.fichasHub;

            $.connection.hub.start().done(function () {
                getAll();
            });

            hubNotify.client.refreshFichasData = function () {
                getAll();
            };
        });

        function getAll() {
            var model = $('#dataModel');
            $.ajax({
                url: '/Fichas/GetFichasData',
                contentType: 'application/html ; charset:utf-8',
                type: 'GET',
                dataType: 'html',
                success: function (result) { model.empty().append(result); }
            });
        }
    </script>
}

ProyectoATECA/Views/Fichas/Llamar.cshtml
@model ProyectoATECA.Models.Ficha

@{
    ViewBag.Title = "Llamar";
    ViewData["llamado"] = "Si";

}

<h4>Llamar</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h2>¿Está seguro que desea llamar a esta ficha?</h2>
    <h2>@Model.codigoFicha.ToString()</h2>
    <h2>@Model.ID_servicio.ToString()</h2>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_servicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_servicio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.codigoFicha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codigoFicha)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.fecha)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.fecha)
        </dd>
    </dl>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_ficha)

    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.ID_servicio, "ID_servicio", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ID_servicio", null, htmlAttributes: new { @class = "form-control", })
        </div>
    </div>

    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.codigoFicha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.codigoFicha, new { htmlAttributes = new { @class = "form-control", } })
        </div>
    </div>

    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control", } })
        </div>
    </div>

    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.atendido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.atendido, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.llamado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.llamado, new { @Value = ViewData["llamado"], htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>


    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.tipoFicha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.tipoFicha, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Llamar" class="btn btn-default" />
        </div>
    </div>
</div>

}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

ProyectoATECA/Views/Fichas/_FichasData.cshtml
@model IEnumerable<ProyectoATECA.Models.Ficha>

@{
    /**/

    ViewBag.Title = "Fichas";

}
<div class="alert-dark">
    <h2>Fichas en cola</h2>
</div>
    <br>
    <p>

    </p>
    <table class="table table-hover">
        <tr class="table-dark table-bordered">
            <th>
                @Html.DisplayNameFor(model => model.codigoFicha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.atendido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.llamado)
            </th>
            <th>
                Servicio
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tipoFicha)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.codigoFicha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.atendido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.llamado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Servicio.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tipoFicha)
                </td>

            </tr>
        }
    </table>
    <br>
    <div class="row">
        <div class="col-md-4">
            @Html.ActionLink("Llamar", "Llamar", "Fichas", new { id = @Model.FirstOrDefault()?.ID_ficha }, new { @class = "btn btn-info" })

            @Html.ActionLink("Atender", "Create", "HistorialAtendidos", new { @ID_ficha = @Model.FirstOrDefault()?.ID_ficha, @ID_servicio = @Model.FirstOrDefault()?.ID_servicio, @codigo = @Model.FirstOrDefault()?.codigoFicha }, new { @class = "btn btn-success" })

            @Html.ActionLink("Eliminar", "Eliminar", "Fichas", new { id = @Model.FirstOrDefault()?.ID_ficha }, new { @class = "btn btn-danger" })
        </div>
    </div>